// Static pages are plain HTML files, not React routes: legal pages must be
// readable by crawlers and reviewers without executing the bundle.
// Newest released version, read once from the appcast baked into this image
// (generate_appcast writes newest-first; a release redeploys the site).
let cachedLatest: string | null | undefined;
function latestVersion(): string | null {
  if (cachedLatest === undefined) {
    let xml = "";
    try {
      xml = require("fs").readFileSync("appcast.xml", "utf8");
    } catch {}
    cachedLatest =
      xml.match(/<sparkle:shortVersionString>(\d+\.\d+\.\d+)</)?.[1] ?? null;
  }
  return cachedLatest;
}

const pages: Record<string, string> = {
  "/main.js": "dist/main.js",
  // The mark, generated by brand/build.sh. SVG is the one the page uses: it is
  // ~8KB against the old icon's 600KB and stays crisp at any size. The PNGs are
  // for the places that cannot take a vector — iOS home screens and link
  // unfurls.
  "/icon.svg": "icon.svg",
  // Dark-mode favicon: the tab strip follows the OS theme, not the page.
  "/icon-dark.svg": "icon-dark.svg",
  // Groundless, for the landing page's own dark field.
  "/mark.svg": "mark.svg",
  "/icon-180.png": "icon-180.png",
  "/icon-512.png": "icon-512.png",
  // Newsreader, subset to Latin from the same TTF the Swift client bundles.
  "/newsreader-var.woff2": "newsreader-var.woff2",
  "/privacy": "privacy.html",
  "/self-host": "selfhost.html",
  "/terms": "terms.html",
  // Sparkle update feed, regenerated by passband/make-appcast.sh each release.
  "/appcast.xml": "appcast.xml",
};

const server = Bun.serve({
  port: Number(process.env.PORT ?? 3000),
  async fetch(req) {
    const path = new URL(req.url).pathname;
    const file = pages[path];
    if (file) {
      // The font is the only asset worth caching hard: it is the largest thing
      // on the render path and it changes about once a release cycle. A week
      // is long enough to matter and short enough that no URL hash is needed.
      return new Response(Bun.file(file), {
        headers: path.endsWith(".woff2")
          ? { "Cache-Control": "public, max-age=604800" }
          : undefined,
      });
    }
    // The homepage's download button. The appcast in this image is the truth
    // about what shipped last (newest entry first), so redirect through the
    // versioned URL below; with no releases yet, fall back to the releases page.
    if (path === "/download" || path === "/download/latest") {
      const version = latestVersion();
      return Response.redirect(
        version
          ? `/download/Passband-${version}.zip`
          : "https://github.com/braelyn-ai/squelch/releases",
        302,
      );
    }
    // Stable download URLs the appcast can use as its enclosure prefix:
    // /download/Passband-1.2.3.zip redirects to that version's GitHub release
    // asset. The archives live on GitHub, not in this image, so the feed URL
    // outlives any storage choice and the site stays tiny.
    const dl = path.match(/^\/download\/(Passband-(\d+\.\d+\.\d+)\.zip)$/);
    if (dl) {
      return Response.redirect(
        `https://github.com/braelyn-ai/squelch/releases/download/passband-mac-${dl[2]}/${dl[1]}`,
        302,
      );
    }
    return new Response(Bun.file("index.html"));
  },
});

console.log(`passband-site listening on ${server.url}`);
