// Static pages are plain HTML files, not React routes: legal pages must be
// readable by crawlers and reviewers without executing the bundle.
const pages: Record<string, string> = {
  "/main.js": "dist/main.js",
  "/privacy": "privacy.html",
  "/terms": "terms.html",
  // Sparkle update feed, regenerated by passband/make-appcast.sh each release.
  "/appcast.xml": "appcast.xml",
};

const server = Bun.serve({
  port: Number(process.env.PORT ?? 3000),
  async fetch(req) {
    const path = new URL(req.url).pathname;
    const file = pages[path];
    if (file) {
      return new Response(Bun.file(file));
    }
    // Stable download URLs the appcast can use as its enclosure prefix:
    // /download/Passband-1.2.3.zip redirects to that version's GitHub release
    // asset. The archives live on GitHub, not in this image, so the feed URL
    // outlives any storage choice and the site stays tiny.
    const dl = path.match(/^\/download\/(Passband-(\d+\.\d+\.\d+)\.zip)$/);
    if (dl) {
      return Response.redirect(
        `https://github.com/braelyn-ai/squelch/releases/download/passband-v${dl[2]}/${dl[1]}`,
        302,
      );
    }
    return new Response(Bun.file("index.html"));
  },
});

console.log(`passband-site listening on ${server.url}`);
